### ISSUE TITLE
Indexing

### ISSUE THREAD

**Issue by Mastersam07** [LordGhostX/animeX-v2#9]
### Results index
For any search results, the result index show to start counting from 2. But when you follow the index, the downloads seem to be that of 1 index ahead.

![image](https://user-images.githubusercontent.com/31275429/94367468-dd6c8000-0093-11eb-9749-9b2b5175763a.png)

- For the above image, result numbered 4 seems to be that of bleach episode 274-366 and that numbered 5 seems to be that of the whole 366 episodes.
- As shown in the above picture, picking the result numbered 4 fetches me the result of that number 5(4 seems to fetch all 366 episodes which should be for 5)

### Suggestion
- lets the result starts counting from 1

### Likely cause of the issue
- The new script, line 133 and 155 of [animeX.py](https://github.com/LordGhostX/animeX-v2/blob/master/animeX.py)
- The former script, line 123 of [some stable old animeX.py](https://github.com/LordGhostX/animeX-v2/blob/5b986207b9b64a5b2f3af75c33833d0b2bd429dd/animeX.py)
- The lines enumerating the search result. Reverting to the previous method seems to work well as this conflict doesn't arise.

#### You could help look into it or I could check further to ascertain the main cause and send a PR

**Comment by LordGhostX** [comment]
I just reverted the enumeration to the old style, see if it solves the problem on the module

**Comment by Mastersam07** [comment]
Okay. Would check

**Comment by LordGhostX** [comment]
any update on this yet?

**Comment by Preciousomonze** [comment]
💀 bosses

**Comment by LordGhostX** [comment]
omo @Mastersam07 air me sha

**Comment by Mastersam07** [comment]
Hey, it's not like that 😄. Allow me to check, please. I am not sure the result again.

**Comment by Mastersam07** [comment]
Handles like a charm. Thanks for all you do @LordGhostX
